version: '3.8'

services:
  web:
    build:
      context: .
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: mysql://snowtrick:password@db:3306/snowtricks
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - 8888:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/var/www/html/public
    depends_on:
      - web
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: snowtricks
      MYSQL_USER: snowtrick
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: snowtrick
      MYSQL_PASSWORD: password
    depends_on:
      - db
    networks:
      - app-network
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks :
      - app-network

networks:
  app-network:
    driver: bridge
