version: '3.7'
services:
  web:
    image: php:8.2-fpm
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - 8888:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: snowtricks
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ''
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
